import { IconType } from 'react-icons';

import {
    HiArrowRight,
    HiArrowTopRightOnSquare,
    HiArrowUpRight,
    HiCalendarDays,
    HiCheck,
    HiCheckCircle,
    HiChevronDown,
    HiChevronLeft,
    HiChevronRight,
    HiChevronUp,
    HiClipboard,
    HiEnvelope,
    HiExclamationCircle,
    HiExclamationTriangle,
    HiInformationCircle,
    HiLockClosed,
    HiMiniGlobeAsiaAustralia,
    HiMiniQuestionMarkCircle,
    HiMiniXMark,
    HiOutlineArrowPath,
    HiOutlineEye,
    HiOutlineEyeSlash,
    HiOutlineLink,
} from 'react-icons/hi2';

import {
    PiBookBookmarkDuotone,
    PiGridFourDuotone,
    PiHouseDuotone,
    PiImageDuotone,
    PiUserCircleDuotone,
} from 'react-icons/pi';

import { FaDiscord, FaGithub, FaLinkedin, FaXTwitter } from 'react-icons/fa6';

export const iconLibrary: Record<string, IconType> = {
    chevronUp: HiChevronUp,
    chevronDown: HiChevronDown,
    chevronRight: HiChevronRight,
    chevronLeft: HiChevronLeft,
    refresh: HiOutlineArrowPath,
    arrowUpRight: HiArrowUpRight,
    check: HiCheck,
    arrowRight: HiArrowRight,
    helpCircle: HiMiniQuestionMarkCircle,
    infoCircle: HiInformationCircle,
    warningTriangle: HiExclamationTriangle,
    errorCircle: HiExclamationCircle,
    checkCircle: HiCheckCircle,
    email: HiEnvelope,
    globe: HiMiniGlobeAsiaAustralia,
    person: PiUserCircleDuotone,
    grid: PiGridFourDuotone,
    book: PiBookBookmarkDuotone,
    close: HiMiniXMark,
    openLink: HiOutlineLink,
    calendar: HiCalendarDays,
    home: PiHouseDuotone,
    hobbies: PiImageDuotone,
    discord: FaDiscord,
    eye: HiOutlineEye,
    eyeOff: HiOutlineEyeSlash,
    github: FaGithub,
    linkedin: FaLinkedin,
    x: FaXTwitter,
    clipboard: HiClipboard,
    arrowUpRightFromSquare: HiArrowTopRightOnSquare,
    lock: HiLockClosed,
};
